name: Publish Docker image

on:
  push:
    branches: [ main ]
    # Trigger this action only on push events to the main branch.
    # You can adjust this to suit your branching strategy.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Create .env file
      run: echo "DB_HOST=image_build" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      run: docker build --tag ${{ github.repository_owner }}/portal-web:latest .
    - name: Release
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: npm
    - run: npm ci
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        HELM_CHART_PATH: ${{ vars.HELM_CHART_PATH }}
        HELM_REPO_URL: ${{ vars.HELM_REPO_URL }}
        HELM_PROJECT_VALUES_TAG: ${{ vars.HELM_PROJECT_VALUES_TAG }}
        RELEASE_BRANCH: ${{ vars.RELEASE_BRANCH }}

