name: Publish Docker image

on:
  push:
    branches: [ main ]
    # Trigger this action only on push events to the main branch. 
    # You can adjust this to suit your branching strategy.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_TOKEN is a built-in secret that's automatically created by GitHub 
        # to use in your workflow. You can use this token to authenticate in a workflow run.

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/portal-web:latest
